version: '0.9.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack .\src\Orleans.Providers.EntityFramework -c debug -o .\src\Orleans.Providers.EntityFramework\publish
after_build:
artifacts:
 - path: '\src\Orleans.Providers.EntityFramework\publish\*.nupkg'
   name: Orleans.Providers.EntityFramework
   type: NuGetPackage
clone_depth: 1
test_script:
  - cmd: dotnet restore --verbosity m
  - cmd: dotnet test .\test\Orleans.Providers.EntityFramework.UnitTests
on_finish :
  
deploy: off